---

- name: "aws-vault download & install"
  get_url:
    url: "https://github.com/99designs/aws-vault/releases/download/v6.2.0/aws-vault-linux-amd64"
    dest: "/usr/local/bin/aws-vault"
    checksum: "sha256:1d87a634cd22de9c9cf0cbbbd710651622414ecc556e9c91c9acdc5f07329c6e"
    mode: '0755'
  become: true

- name: "aws-vault - Add wsl-open.sh to /usr/local/bin"
  get_url:
    url: "https://raw.githubusercontent.com/4U6U57/wsl-open/master/wsl-open.sh"
    dest: "/usr/local/bin/wsl-open.sh"
    checksum: "sha256:5c96764bcbc3bdc995d5f8100f33d2586e8cbb7d594848dc60ab9b6a012b5a6c."
    mode: '0755'
  become: true

- name: "aws-vault - Symlink xdg-open -> wsl-open.sh"
  file:
    src: "/usr/local/bin/wsl-open.sh"
    path: "/usr/local/bin/xdg-open"
    state: link
  become: true

- name: "aws-vault - set completions in .bashrc"
  lineinfile:
    path: '${HOME}/.bashrc'
    state: present
    line: 'eval "$(aws-vault --completion-script-bash)"'

- name: "aws-vault - set backend to file"
  lineinfile:
    path: '${HOME}/.bashrc'
    state: present
    line: 'export AWS_VAULT_BACKEND=file'

- name: "aws-vault - export AWS_SESSION_TOKEN_TTL"
  lineinfile:
    path: '${HOME}/.bashrc'
    state: present
    line: 'export AWS_SESSION_TOKEN_TTL=10h'
