---

# https://classic.yarnpkg.com/en/docs/install#debian-stable

- name: "yarn - gpg"
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
  become: true

- name: "yarn - ensure yarn.list"
  lineinfile:
    dest: /etc/apt/sources.list.d/yarn.list
    line: 'deb http://dl.yarnpkg.com/debian/ stable main'
    state: present
    create: yes
    owner: root
    group: root
    mode: '0644'
  become: true

- name: "yarn - install via apt"
  apt:
    state: latest
    name: yarn
    update_cache: yes
  become: true
